services:
  app:
    build:
      context: ..
      dockerfile: dockerfile.dev
    container_name: payment-service
    ports:
      - '3010:3010'
      - '9229:9229'
    env_file:
      - ../.env
    environment:
      NODE_ENV: development
      PORT: 3010
      MONGODB_URI: mongodb://mongo:27017/payment
      DOCKER_ENV: 'true'
      MERCADO_PAGO_POS_ID: ${MERCADO_PAGO_POS_ID}
      MERCADO_PAGO_PAYMENT_ACCESS_TOKEN: ${MERCADO_PAGO_PAYMENT_ACCESS_TOKEN}
      MERCADO_PAGO_API_URL: ${MERCADO_PAGO_API_URL}
      AWS_REGION: us-east-1
      AWS_ENDPOINT: http://localstack:4566
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_SQS_CANCEL_PAYMENT_QUEUE_URL: http://localstack:4566/000000000000/cancel-payment-queue
      AWS_SQS_PAYMENT_PAID_QUEUE_URL: http://localstack:4566/000000000000/payment-paid-queue
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_NAMESPACE: default
    volumes:
      - ..:/app
    command: yarn start:dev
    depends_on:
      localstack:
        condition: service_healthy
      mongo:
        condition: service_healthy
      localstack-init:
        condition: service_completed_successfully
    networks:
      - payment-network
    restart: unless-stopped
    profiles:
      - dev

  app-replica:
    build:
      context: ..
      dockerfile: dockerfile.dev
    container_name: payment-service-replica
    ports:
      - '3010:3010'
      - '9229:9229'
    environment:
      NODE_ENV: production
      PORT: 3010
      MONGODB_URI: mongodb://mongo:27017,mongo2:27018/payment?replicaSet=rs0
      MONGODB_WRITE_CONCERN: 2
      DOCKER_ENV: 'true'

      # OpenTelemetry
      OTEL_SDK_DISABLED: 'false'
      OTEL_SERVICE_NAME: 'soat-payment'
      OTEL_RESOURCE_ATTRIBUTES: 'service.namespace=soat,deployment.environment=production'
      OTEL_TRACES_EXPORTER: 'otlp'
      OTEL_METRICS_EXPORTER: 'otlp'
      OTEL_LOGS_EXPORTER: 'otlp'
      OTEL_EXPORTER_OTLP_PROTOCOL: 'http/protobuf'
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'
    volumes:
      - ..:/app
    command: yarn start:dev
    depends_on:
      mongo:
        condition: service_healthy
      mongo2:
        condition: service_healthy
      mongo-init:
        condition: service_completed_successfully
    networks:
      - payment-network
    restart: unless-stopped
    profiles:
      - observability
