global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'soat-payment'
    environment: 'development'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
        labels:
          service: 'otel-collector'

  - job_name: 'soat-payment'
    static_configs:
      - targets: ['otel-collector:8889']
        labels:
          service: 'payment-api'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
        labels:
          service: 'jaeger'

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongo-exporter:9216']
        labels:
          service: 'mongodb'
    scrape_interval: 15s
